src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <infoMessage>Please select a Broker for this Prospect/Client</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this record type to create new Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependancy__c</fullName>
        <label>Dependancy</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dependency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Child</value>
            </filterItems>
            <infoMessage>Please select the child case that needs to finish before this case is started</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skip_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Case</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <businessProcess>Child</businessProcess>
        <label>Child</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <businessProcess>Parent</businessProcess>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Template__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <picklist>
            <picklistValues>
                <fullName>Account Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wellness Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependency__c</fullName>
        <label>Dependency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fixed_SLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fixed SLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Case_Template_Group__c</referenceTo>
        <relationshipLabel>Case Templates</relationshipLabel>
        <relationshipName>Case_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation_Size__c</fullName>
        <description>The size of the organization used in SAL calc</description>
        <label>Organisation Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA1__c</fullName>
        <label>SLA1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA2__c</fullName>
        <label>SLA2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Case Template</label>
    <nameField>
        <label>Case Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template</pluralLabel>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <label>Child</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Template_Group__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Case Template Group</label>
    <nameField>
        <label>Case Template Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Associated_System_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated System Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Name__c</fullName>
        <formula>Broker_Code__r.Broker__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Group__r.Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Del Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>Unique code used to identify the product.</description>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name_System__c</fullName>
        <label>Product Name System (Long)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ancillary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary &amp; Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary &amp; Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary, Medical &amp; Hospital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/caseTemplateBuilder.cls
public class caseTemplateBuilder{
    
    public List<Case_Template_Group__c> ctgList {get;set;}
    public Map<Integer, Case> newCases {get;set;}
    
    public Integer newCasesSize {get;set;}
    public Integer ctgListSize {get;set;}
    
    public Id objectId {get;set;}
    public string objectName {get;set;}
    public Integer NumberOfEmployees {get;set;}
    
    public BusinessHours bh {get;set;}
    
    public Id accountId {get;set;}
    public Account acc {get;set;}
    public Id selectedTemplate {get;set;}
    public Map<String, Id> assignTo {get;set;}
    public Map<String, Id> recordTypes {get;set;}
    
    public Boolean error {get;set;}
    public String errorMsg {get;set;}
    
    public DateTime startingDate {get;set;}
    
    //objects for information
    public List<Group__c> searchGroup {get;set;}
    public List<Section__c> searchSection {get;set;}
    public List<Opportunity> searchOpportunity {get;set;}
    public List<Account> searchClient {get;set;}
    public List<Section_Product__c> searchProduct {get;set;}
    //END objects for information
    
    public caseTemplateBuilder(){
        
        ctgList = new List<Case_Template_Group__c>();
        assignTo = new Map<String, Id>();
        newCases = new Map<Integer, Case>();
        
        startingDate = system.NOW();
        
        objectId = ApexPages.CurrentPage().getParameters().get('oid');
        objectName = ApexPages.CurrentPage().getParameters().get('sObjectType');
        if(objectName == 'ClientMaintenance'){
            objectName = 'Client Maintenance';
        }
        if(objectName != null){
            populateCTG();
        }
        accountId = ApexPages.CurrentPage().getParameters().get('aid');
        if(accountId != null){
            List<Account> acList = new list<Account>([SELECT Name FROM Account WHERE Id=:accountId]);
            if(!acList.isEmpty()){
                acc = acList[0];
            }
        }
        
        system.debug('Object Id = ' + objectId + ' || Object Name = ' + objectName);
        
        if(objectId != null && objectName != null){
            if(objectName == 'Opportunity' || objectName == 'Renewal' || objectName == 'Client Maintenance'){                
                searchOpportunity = new List<Opportunity>([SELECT Id, Name, AccountId, Account.Name, RecordType.Name, CloseDate, CreatedDate, Owner.Alias FROM Opportunity WHERE Id=:objectId ]);
            }else if(objectName == 'Client'){
                searchClient = new List<Account>([SELECT Id, Name, Phone, RecordType.Name, BillingState, Owner.Alias, Default_Broker__r.Name FROM Account WHERE Id=:objectId]);
            }else if(objectName == 'Group'){
                searchGroup = new List<Group__c>([SELECT Id, Name, Client_Name__c, Group_Number__c, Rate_Code__c, Start_Date__c, Is_Active__c FROM Group__c WHERE Id=:objectId]);
            }else if(objectName == 'Section'){
                searchSection = new List<Section__c>([SELECT Id, Name, Client_Name__c, Associated_System_Section__r.Name, Broker_Name__c, Date_Closed__c, Group__r.Name, Member__c FROM Section__c WHERE Id=:objectId]);
            }else if(objectName == 'Product'){
                searchProduct = new List<Section_Product__c>([SELECT Id, Name, Product_Code__c, Product_Name_System__c, Product_Type__c, Rate_Code__c, Start_Date__c FROM Section_Product__c WHERE Id=:objectId]);
            }
        }
        
        List<BusinessHours> bhList = new List<BusinessHours>([SELECT Id FROM BusinessHours WHERE Name = 'GU Default']);
        if(!bhList.isEmpty()){
            bh = bhList[0];
        }
        
        checkSize();
        
        error = false;
        
        List<Group> qList = new List<Group>([SELECT Id, Name FROM Group WHERE Type = 'Queue']);
        if(!qList.isEmpty()){
            for(Group q:qList){
                assignTo.put(q.Name, q.Id);
            }
        }
        
        recordTypes = new Map<String, Id>();
        List<RecordType> rtList = new List<RecordType>([SELECT Id, Name FROM RecordType WHERE sObjectType = 'Case' AND (Name = 'Parent' OR Name = 'Child') LIMIT 2]);
        if(!rtList.isEmpty()){
            for(RecordType rt:rtList){
                recordTypes.put(rt.Name, rt.Id);
            }
        }
        
    }
    
    public Void populateCTG(){
        
        error = false;
        
        if(objectName == null || objectName == ''){
            error = true;
            errorMsg = 'An object type has not been selected. Please select an object type before proceeding.';
            ctgList = new List<Case_Template_Group__c>();
            newCases = new Map<Integer, Case>();
        }else{
            ctgList = new List<Case_Template_Group__c>([SELECT Id, Name FROM Case_Template_Group__c WHERE IsActive__c = true AND Object__c INCLUDES(:objectName) ORDER BY Name]);
        }
        
        checkSize();
    }
    
    public Void checkSize(){
        newCasesSize = newCases.size();
        ctgListSize = ctgList.size();
    }
    
    public PageReference findCaseTemplates(){
        
        newCases = new Map<Integer, Case>();
        error = false;
        
        if(accountId != null){
            List<Account> acList = new List<Account>([SELECT Id, Name, OwnerId, NumberOfEmployees FROM Account WHERE Id=:accountId LIMIT 1]);
            if(!acList.isEmpty()){
                for(Account a:acList){
                    assignTo.put('AM', a.OwnerId);
                    NumberOfEmployees = a.NumberOfEmployees;
                }
            }
        }
        
        List<Case_Template__c> ctList = new List<Case_Template__c>([SELECT Fixed_SLA__c, SLA1__c, SLA2__c, Id, Name, Code__c, Dependency__c, Description__c, Assigned_To__c, Type__c, Organisation_Size__c FROM Case_Template__c WHERE Group__c =:selectedTemplate ORDER BY Code__c ASC]);
        if(!ctList.isEmpty()){
            
            for(Case_Template__c ct:ctList){
                Case c = new Case();
                if(acc != null && acc.Name != null){
                    c.Subject = acc.Name + ' - ' + ct.Name;
                }else{
                    c.Subject = ct.Name;
                }
                c.Type = ct.Type__c;
                c.Code__c = ct.Code__c;
                c.Dependancy__c = ct.Dependency__c;
                c.Description = ct.Description__c;
                c.Skip_Case__c = false;
                c.Team__c = ct.Assigned_To__c;
                
                if(bh != null){
                    c.BusinessHoursId = bh.Id;
                }
                
                if(c.Code__c == 0 && recordTypes.containsKey('Parent')){
                    c.RecordTypeId = recordTypes.get('Parent');
                    if(objectName == 'Opportunity' || objectName == 'Renewal' || objectName == 'Client Maintenance'){
                        c.Opportunity_Renewal__c = objectId;
                    }else if(objectName == 'Client'){
                        c.AccountId = objectId;
                    }else if(objectName == 'Group'){
                        c.Group__c = objectId;
                    }else if(objectName == 'Section'){
                        c.Section__c = objectId;
                    }else{
                        error = true;
                        errorMsg = 'Could not associate the parent case with an object. Please ensure the object name and the selected record match up before proceeding.';
                        return null;
                    }
                }else if(recordTypes.containsKey('Child')){
                    c.RecordTypeId = recordTypes.get('Child');
                }
                
                if(c.Code__c > 0){
                    if(NumberOfEmployees != null && NumberOfEmployees > 0 && !ct.Fixed_SLA__c && ct.SLA2__c != null){
                        if(NumberOfEmployees >= ct.Organisation_Size__c){
                            c.SLA_Days__c = ct.SLA2__c;
                        }else{
                            c.SLA_Days__c = ct.SLA1__c;
                        }
                    }else{
                        c.SLA_Days__c = ct.SLA1__c;
                    }
                    
                    if(assignTo.containsKey(ct.Assigned_To__c)){
                        c.OwnerId = assignTo.get(ct.Assigned_To__c);
                    }
                }
                
                newCases.put(Integer.valueOf(c.Code__c), c);
            }
            
            //Recalculate the SLAs
            recalcSLAs();
            
        }
        
        system.debug('Cases List ' + newCases);
        
        checkSize();
        return null;
        
    }
    
    public Void recalcSLAs(){
        //Calculate the SLAs
        if(!newCases.isEmpty() && newCases.containsKey(0) && newCases.get(0).Estimated_Start_Date__c != null){
            startingDate = newCases.get(0).Estimated_Start_Date__c;
        }else{
            startingDate = system.NOW();
        }
        
        guUtil slap = new guUtil();
        newCases = slap.recalcSLA(newCases, bh, startingDate);
    }
    
    public PageReference submit(){
        
        error = false;
        List<Case> insertList = new List<Case>();
        Case parentCase;
        
        for(Case c:newCases.values()){
            if(c.Code__c == 0){
                parentCase = c;
            }else{
                insertList.add(c);
            }
        }
        
        try{
            insert parentCase;
        }catch(Exception e){
            system.debug('Parent Case insert failed ' + parentCase);
            error = true;
            errorMsg = 'There was an error trying to insert the parent case. Please try again, and if the error persists please contact a system administrator to check the data.';
            return null;
        }
        
        for(Case c:insertList){
            c.ParentId = parentCase.Id;
            if(c.Skip_Case__c){
                c.Status = 'Not Required';
            }
        }
        
        try{
            insert insertList;
        }catch(Exception e){
            system.debug('Child Cases insert failed ' + insertList);
            error = true;
            errorMsg = 'There was an error trying to insert the child cases. Please try again, and if the error persists please contact a system administrator to check the data.';
            return null;
        }
        
        PageReference returnRecord = new PageReference('/' + objectId);
        return returnRecord;
        
    }
    
    public List<SelectOption> getGroups() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Please Select a Group--'));
        for(Case_Template_Group__c g:ctgList){
            options.add(new SelectOption(g.Id,g.Name));
        }

        return options;
    }
    
    public List<SelectOption> getListOfObjects() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Please Select an Object--'));
        Schema.DescribeFieldResult fieldResult = Case_Template_Group__c.Object__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        } 
        
        return options;
    }
    
}