src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Broker</fullName>
        <active>true</active>
        <description>Use this record type to create new Brokers</description>
        <label>Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this record type to create new Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <formula>Opportunity__r.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the copy (calculated via the Group Version Number object which is updated via the Group Number)</description>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <infoMessage>Please select a broker for this opportunity</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Broker)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <displayFormat>OPP-{000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accountExtension.cls
public class accountExtension {

    private final Account acct;
    public List<Opportunity> renewalList {get;set;}
    public List<Opportunity> newList {get;set;}
    public List<Opportunity> cmList {get;set;}
    public List<Opportunity> brokerList {get;set;}
    public List<Group__c> gList {get;set;}
    public List<Group__c> allgList {get;set;}
    
    public Id renewalId {get;set;}
    public Id opportunityId {get;set;}
    
    public String recordId {get;set;}

    public accountExtension(ApexPages.StandardController stdController) {
        if(!test.isRunningTest()){
            stdController.AddFields(new List<String>{'RecordType.Name'});
        }
        this.acct = (Account)stdController.getRecord();
        
        recordId = apexpages.currentpage().getparameters().get('id');
        
        List<RecordType> rtList = new List<RecordType>([SELECT Id, Name FROM RecordType WHERE sObjectType = 'Opportunity' AND (Name = 'Opportunity' OR Name = 'Renewal')]);
        if(!rtList.isEmpty()){
            for(RecordType rt:rtList){
                if(rt.Name == 'Opportunity'){
                    opportunityId = rt.Id;
                }else if(rt.Name == 'Renewal'){
                    renewalId = rt.Id;
                }
            }
        }
        
        if(acct.RecordType.Name != 'Broker'){
            renewalList = new List<Opportunity>([SELECT Id, Name, Amount, StageName, CloseDate, Opportunity_Number__c, CreatedBy.Alias FROM Opportunity WHERE RecordTypeId IN (SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Renewal') AND AccountId=:acct.Id]);
            newList = new List<Opportunity>([SELECT Id, Name, Amount, StageName, CloseDate, Opportunity_Number__c, CreatedBy.Alias FROM Opportunity WHERE RecordTypeID IN (SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Opportunity') AND AccountId=:acct.Id]);
            cmList = new List<Opportunity>([SELECT Id, Name, Amount, StageName, CloseDate, Opportunity_Number__c, CreatedBy.Alias FROM Opportunity WHERE RecordTypeId IN (SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Client Maintenance') AND AccountId=:acct.Id]);
        }else{
            brokerList = new List<Opportunity>([SELECT Id, Name, Amount, StageName, CloseDate, Opportunity_Number__c, CreatedBy.Alias, Account.Name, AccountId FROM Opportunity WHERE RecordTypeId IN (SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Opportunity') AND Broker__c=:acct.Id ORDER BY Account.Name]);
        }
        
        gList = new List<Group__c>([SELECT Id, Name, Group_Number__c, Start_Date__c, Rate_Code__c, Is_Active__c, Version__c FROM Group__c WHERE Client_Id__c =:recordId AND (Is_Active__c = 'Active' OR Is_Active__c = 'Pending') ORDER BY Name, Version__c DESC]);
        allgList = new List<Group__c>([SELECT Id, Name, Group_Number__c, Start_Date__c, Rate_Code__c, Is_Active__c, Version__c FROM Group__c WHERE Client_Id__c =:recordId ORDER BY Group_Number__c, Version__c DESC]);
    }
}