src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this record type to create new Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Copies</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Not_Calculate_Renewal_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Prevent the system from calculating the renewal date automatically (this can be used in special circumstances where the renewal date needs to be manually set to a date that does not meet standard procedural requirements e.g. can not wait 12 months)</inlineHelpText>
        <label>Do Not Calculate Renewal Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field (system) to distinguish whether the record has been edited using the publish wizard. Tells the system to change the record type to active.</description>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity/Renewal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>The date that this record was superseded by publishing a newer version (this is a system field and can not be edited).</inlineHelpText>
        <label>Discard Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Processed_Time__c</fullName>
        <description>When the renewal was created (either manually or automatically). Once this field is populated, the scheduler will not clone it automatically</description>
        <inlineHelpText>When the renewal was created (either manually or automatically). Once this field is populated, the scheduler will not clone it automatically</inlineHelpText>
        <label>Renewal Processed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal_Trigger_Date__c</fullName>
        <description>This is the date that the system will create a new renewal (if one has not been created manually already).</description>
        <inlineHelpText>This is the date that the system will create a new renewal (if one has not been created manually already).</inlineHelpText>
        <label>Renewal Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the copy (calculated via the Group Version Number object which is updated via the Group Number)</description>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <description>A draft group (not yet implimented)</description>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Replaced</fullName>
        <active>true</active>
        <description>When a group is superceded</description>
        <label>Replaced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Group_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Contact</label>
    <nameField>
        <displayFormat>GRPCON{000000}</displayFormat>
        <label>Group Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This field is automatically calculated based on the start date + renewal months</inlineHelpText>
        <label>Effective Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Requested Product</label>
    <nameField>
        <label>Requested Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sections (Clone of)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
Group__r.Is_Active__c = &apos;Draft&apos;, &apos;Draft&apos;,
IF(
Group__r.Is_Active__c = &apos;Pending&apos;, &apos;Pending&apos;,
IF(
Date_Closed__c &lt;= TODAY(), &apos;Closed&apos;, Group__r.Is_Active__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Contact__c.object
<CustomObject>
    <description>Contacts to Section junction object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Section_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Section_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section Contact</label>
    <nameField>
        <displayFormat>SECCON{000000}</displayFormat>
        <label>Section Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipName>Section_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
OR(
AND(
NOT(ISBLANK(Hospital_Date_Withdrawn__c)),
Hospital_Date_Withdrawn__c &lt;= TODAY()),
AND(
NOT(ISBLANK(Medical_Date_Withdrawn__c)),
Medical_Date_Withdrawn__c &lt;= TODAY()),
AND(
NOT(ISBLANK(Ancillary_Date_Withdrawn__c)),
Ancillary_Date_Withdrawn__c &lt;= TODAY()))
,&apos;Component Withdrawn&apos;,&apos;Active&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product_Link__c.object
<CustomObject>
    <description>Junction object between section and section product tables</description>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Section__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
Section__r.Status__c == &apos;Draft&apos;, Section__r.Status__c,
IF(
Date_closed__c &lt;= TODAY(), &apos;Closed&apos;,
IF(
Product__r.Status__c = &apos;Component Withdrawn&apos;,&apos;Component Withdrawn&apos;,
IF(
Withdrawn_Date__c &lt;= TODAY(), &apos;Withdrawn&apos;,
IF(
Start_Date__c &gt; TODAY(), &apos;Pending&apos;,
Section__r.Status__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Section__r.Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section Product Link</label>
    <nameField>
        <label>Section Product Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section Product Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/renewalProcess.cls
global class renewalProcess {
    
    //Maps/Lists for populating with new data
    public Map<Id, Opportunity> opMapNew {get;set;}
    public Map<Id, Group__c> grpMapNew {get;set;}
    public Map<Id, Section__c> secMapNew {get;set;}
    public Map<Id, Section_Product_Link__c> splMapNew {get;set;}
    public Map<Id, Group_Contact__c> grpConMapNew {get;set;}
    public Map<Id, Section_Contact__c> secConMapNew {get;set;}
    
    //ref objects
    public Map<String, Id> rtMap {get;set;}
    public String soql {get;set;}
    public List<Group__c> grpList {get;set;}
    global Id newId {get;set;}
    public Set<Id> opIds {get;set;}
    
    //Main process for Scheduler
    global void processSchedule(String requirement, String inclusion, String recordType, String obj){
        
        //create instances of all the maps
        opMapNew = new Map<Id, Opportunity>();
        grpMapNew = new Map<Id, Group__c>();
        secMapNew = new Map<Id, Section__c>();
        splMapNew = new Map<Id, Section_Product_Link__c>();
        grpConMapNew = new Map<Id, Group_Contact__c>();
        secConMapNew = new Map<Id, Section_Contact__c>();
        opIds = new Set<id>();
        rtMap = new Map<String, Id>();
        
        if(obj == 'Group__c'){

            if(requirement == 'batch'){
                //grpList = new List<Group__c>([SELECT Id FROM Group__c WHERE Is_Active__c = 'Active' AND Renewal_Trigger_Date__c <= TODAY AND Renewal_Processed_Time__c = null ORDER BY Renewal_Trigger_Date__c ASC]);
                soql = Util.getCreatableFieldsSOQL('group__c','Is_Active__c =\'Active\' AND Renewal_Trigger_Date__c <= TODAY AND Renewal_Processed_Time__c = null ORDER BY Renewal_Trigger_Date__c ASC', null);
                
            }else{
                //grpList = new List<Group__c>([SELECT Id FROM Group__c WHERE Id=:requirement]);
                soql = Util.getCreatableFieldsSOQL('group__c','id=\'' + requirement + '\'', null);
            }
            grpList = (List<Group__c>)Database.query(soql);
            
            //-----Record Types
                List<RecordType> rtList = new List<RecordType>([SELECT id, Name, sObjectType FROM RecordType WHERE ((Name = 'Renewal' OR Name = 'Client Maintenance') AND sObjectType = 'Opportunity') OR ((Name = 'Group' OR Name = 'Draft') AND sObjectType = 'Group__c')]);
                for(RecordType rt:rtList){
                    rtMap.put(rt.Name, rt.Id);
                }
            
            //-----Opportunity
                //Build a list of opportunity IDs to clone
                for(Group__c g:grpList){
                    opIds.add(g.Opportunity__c);
                }
                
                if(inclusion == 'with'){
                    //List<Opportunity> opList = new List<Opportunity>([SELECT Id, Account.Name FROM Opportunity WHERE Id IN:opIds]);
                    soql = Util.getCreatableFieldsSOQL('opportunity','id IN :opIds', 'Account.Name');
                    List<Opportunity> opList = (List<Opportunity>)Database.query(soql);
                    for(Opportunity op:opList){
                        //perform clone
                        Opportunity oNew = op.clone(false, true);
                        
                        oNew.Clone_Of__c = op.Id;
                        oNew.RecordTypeId = rtMap.get(recordType);
                        oNew.StageName = 'New';
                        if(recordType == 'Client Maintenance'){
                            oNew.Name = recordType + ' - ' + getLongDate() + ' - ' + oNew.Account.Name;
                            oNew.CloseDate = system.Today().addMonths(2);
                        }else if(recordType == 'Renewal'){
                            oNew.Name = recordType + ' - ' + system.Today().Year() + ' - ' + op.Account.Name;
                            oNew.CloseDate = system.Today().addMonths(4);
                        }
                        
                        opMapNew.put(op.Id, oNew);
                    }
                }
                
                //insert opportunities
                    insert opMapNew.values();
            
            //-----Group
                for(Group__c g :grpList){
                    Group__c gNew = g.clone(false, true);
                    
                    gNew.Clone_of__c = g.Id;
                    if(recordType == 'Renewal'){
                        gNew.Do_Not_Calculate_Renewal_Date__c = false;
                    }else{
                        gNew.Do_Not_Calculate_Renewal_Date__c = true;
                    }
                    gNew.Renewal_Processed_Time__c = null;
                    if(inclusion == 'without'){
                        gNew.Group_Number__c = null;
                    }
                    if((recordType == 'Client Maintenance' || recordType == 'Renewal') && rtMap.containsKey('Draft') && inclusion != 'without'){
                        gNew.RecordTypeId = rtMap.get('Draft');
                    }
                    if(inclusion == 'with' && gNew.Opportunity__c != null){
                        gNew.Opportunity__c = opMapNew.get(g.Opportunity__c).Id;
                    }else if(inclusion == 'without' && gNew.Opportunity__c != null){
                        gNew.Opportunity__c = g.Opportunity__c;
                    }
                    //change any other Group fields that require manipulation
                    gNew.Start_Date__c = null;
                    gNew.Renewal_Date__c = null;
                    gNew.Version__c = null;
                    
                    grpMapNew.put(g.Id, gNew);
                }
                
                //insert grpMapNew
                insert grpMapNew.values();
        }
        
        //-----Sections
            if(obj == 'Section__c'){
                //secList = [SELECT Id FROM Section__c WHERE Id=:requirement];
                soql = Util.getCreatableFieldsSOQL('Section__c','id=\'' + requirement + '\' AND Status__c != \'Closed\'', null); 
            }else{
                //secList = [SELECT Id FROM Section__c WHERE Group__c IN :grpList];
                soql = Util.getCreatableFieldsSOQL('Section__c','Group__c IN :grpList AND Status__c != \'Closed\'', null);
            }
            List<Section__c> secList = (List<Section__c>)Database.query(soql);
            
            for(Section__c s:secList){
                Section__c sNew = s.clone(false, true);
                
                //Any manual removals between versions
                if(obj == 'Group__c'){
                    sNew.Group__c = grpMapNew.get(s.Group__c).Id;
                }else{
                    sNew.Group__c = s.Group__c;
                }
                sNew.Clone_of__c = s.Id;
                
                //add to map with sOg as key (for child clone ref)
                secMapNew.put(s.Id, sNew);
            }
            
            //insert sections
            insert secMapNew.values();
            
        //-----Section Products Link
            //secProLinkList = [SELECT Id FROM Section_Product_Link__c WHERE Product__r.Section__c IN :secList];
            soql = Util.getCreatableFieldsSOQL('Section_Product_Link__c','Section__c IN :secList AND Status__c != \'Closed\'', null);
            List<Section_Product_Link__c> secProLinkList = (List<Section_Product_Link__c>)Database.query(soql);
            
            for(Section_Product_Link__c spl:secProLinkList){
                Section_Product_Link__c splNew = spl.clone(false, true);
                
                //Any manual removals between versions
                splNew.Section__c = secMapNew.get(spl.Section__c).Id;
                splNew.Product__c = spl.Product__c;
                
                //add to map with sOg as key (for child clone ref)
                splMapNew.put(spl.Id, splNew);
            }
            
            //insert section product links
            insert splMapNew.values();
       
       if(obj == 'Group__c'){     
            //-----Group Contacts
                //grpContacts = [SELECT Id FROM Group_Contact__c WHERE Group IN :groList];
                soql = Util.getCreatableFieldsSOQL('Group_Contact__c','Group__c IN :grpList', null);
                List<Group_Contact__c> grpConList = (List<Group_Contact__c>)Database.query(soql);
                
                for(Group_Contact__c grpCon:grpConList){
                    Group_Contact__c grpConNew = grpCon.clone(false, true);
                    
                    //Any manual removals between versions
                    grpConNew.Contact__c = grpCon.Contact__c;
                    grpConNew.Group__c = grpMapNew.get(grpCon.Group__c).Id;
                    
                    //add to map with sOg as key (for child clone ref)
                    grpConMapNew.put(grpCon.Id, grpConNew);
                }
                
                //insert group contacts
                insert grpConMapNew.values();
            }
        
        //-----Section Contacts
            
            if(!secList.isEmpty()){
                //secConList = [SELECT Id FROM Section_Contact__c WHERE Section__c IN :secList];
                soql = Util.getCreatableFieldsSOQL('Section_Contact__c','Section__c IN :secList', null);
                List<Section_Contact__c> secConList = (List<Section_Contact__c>)Database.query(soql);
            
            
                for(Section_Contact__c secCon:secConList){
                    Section_Contact__c secConNew = secCon.clone(false, true);
                    
                    //Any manual removals between versions
                    secConNew.Contact__c = secCon.Contact__c;
                    secConNew.Section__c = secMapNew.get(secCon.Section__c).Id;
                    
                    //add to map with sOg as key (for child clone ref)
                    secConMapNew.put(secCon.Id, secConNew);
                }
                
                //insert section contacts
                insert secConMapNew.values();
            }
            
        //Update original group records
            if(obj == 'Group__c' && recordType == 'Renewal'){
                for(Group__c og:grpList){
                    og.Renewal_Processed_Time__c = system.NOW();
                }
                update grpList;
            }
            
         //Set the newGroupId/newSecId if it is a single clone
             if(requirement != 'batch' && obj == 'Group__c'){
                 newId = grpMapNew.get(requirement).Id;
             }else if(obj == 'Section__c'){
                 newId = secMapNew.get(requirement).Id;
             }
    }
    
    
    global String closeActiveGroup(Group__c g, Date publishDate){
        
        Id recordType;
        List<RecordType> rtList = new List<RecordType>([SELECT Id FROM RecordType WHERE sObjectType = 'Group__c' AND Name = 'Replaced']);
        if(!rtList.isEmpty()){
            recordType = rtList[0].Id;
            List<Group__c> gList = new List<Group__c>([SELECT Id FROM Group__c WHERE Id=:g.Id]);
            if(!gList.isEmpty()){
                Group__c updateG = gList[0];
                if(system.TODAY() >= publishDate){
                    updateG.RecordTypeId = recordType;
                }
                updateG.Renewal_Date__c = publishDate;
                updateG.IsPublishWizard__c = true;
                system.debug(updateG);
                try{
                    update updateG;
                }catch(Exception e){
                    system.debug('Could not update group record ' + updateG);
                    String msg = 'Could not process the closing of the active group. Please perform the action manually before proceeding to publish.';
                    return msg;
                }
            }else{
                String msg = 'Could not process the closing of the active group. Please perform the action manually before proceeding to publish.';
                return msg;
            }
        }else{
            String msg = 'The record type does not exist.';
            return msg;
        }
        
        String msg = 'success';
        return msg;
    }
    
    public String getLongDate() {
        Datetime cDT = System.now();
        String LongDate = cDT.format('MMMM d, yyyy');
        return LongDate;
    }

    global String discardGroup(Id groupId){
        String returnMessage = '';
        Group__c updateGroup = new Group__c(Id = groupId, Start_Date__c = system.Today(), Renewal_Date__c = system.Today(), IsPublishWizard__c = true);

        try{
            update updateGroup;
        }catch(Exception e){
            returnMessage = e.getMessage();
            return returnMessage;
        }

        return returnMessage;
    }
  
}