src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <infoMessage>Please select a Broker for this Prospect/Client</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this record type to create new Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Template_Group__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Case Template Group</label>
    <nameField>
        <label>Case Template Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <formula>Opportunity__r.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Associated_System_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated System Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Name__c</fullName>
        <formula>Broker_Code__r.Broker__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <formula>Group__r.Opportunity__r.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Group__r.Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Del Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/caseTemplateLanding.cls
public class caseTemplateLanding{
    
    //Error messages
    public Boolean error {get;set;}
    public String errorMsg {get;set;}
    //END Error messages
    
    public string objectName {get;set;}
    
    //Search elements
    public String searchCriteria {get;set;}
    public List<Group__c> searchGroup {get;set;}
    public List<Section__c> searchSection {get;set;}
    public List<Opportunity> searchOpportunity {get;set;}
    public List<Account> searchClient {get;set;}
    public List<Section_Product__c> searchProduct {get;set;}
    public Integer resultSize {get;set;}
    //END Search elements
    
    public caseTemplateLanding(ApexPages.StandardController stdController){
        
        searchCriteria = '';
        resultSize = 0;
        
    }
    
    public PageReference searchSF(){
        
        system.debug('Made it');
        error = false;
        
        if(searchCriteria != null && searchCriteria != '' && objectName != null && objectName != '' && objectName != 'None'){
            String searchVariable = '%' + searchCriteria + '%';
            if(objectName == 'Opportunity' || objectName == 'Renewal' || objectName == 'Client Maintenance'){                
                searchOpportunity = new List<Opportunity>([SELECT Id, Name, AccountId, Account.Name, RecordType.Name, CloseDate, CreatedDate, Owner.Alias FROM Opportunity WHERE Account.Name LIKE:searchVariable AND RecordType.Name =:objectName ]);
                resultSize = searchOpportunity.size();
                searchClient = null;
                searchGroup = null;
                searchSection = null;
                searchProduct = null;
            }else if(objectName == 'Client'){
                searchClient = new List<Account>([SELECT Id, Name, Phone, RecordType.Name, BillingState, Owner.Alias, Default_Broker__r.Name FROM Account WHERE Name LIKE:searchVariable]);
                resultSize = searchClient.size();
                searchOpportunity = null;
                searchGroup = null;
                searchSection = null;
                searchProduct = null;
            }else if(objectName == 'Group'){
                searchGroup = new List<Group__c>([SELECT Id, Name, Client_Id__c, Client_Name__c, Group_Number__c, Rate_Code__c, Start_Date__c, Is_Active__c FROM Group__c WHERE Client_Name__c LIKE:searchVariable]);
                resultSize = searchGroup.size();
                searchOpportunity = null;
                searchClient = null;
                searchSection = null;
                searchProduct = null;
            }else if(objectName == 'Section'){
                searchSection = new List<Section__c>([SELECT Id, Name, Client_Id__c, Client_Name__c, Associated_System_Section__r.Name, Broker_Name__c, Date_Closed__c, Group__r.Name, Member__c FROM Section__c WHERE Client_Name__c LIKE:searchVariable]);
                resultSize = searchSection.size();
                searchOpportunity = null;
                searchClient = null;
                searchGroup = null;
                searchProduct = null;
            }else{
                error = true;
                errorMsg = 'There was an error understanding which object you wish to create cases for. Please ensure an object is specified and try again. If the error persists please contact an administrator.';
                return null;
            }
        }else{
            error = true;
            errorMsg = 'This search requires that both the Object be specified as we  as the search criteria box have a value. Please ensure these fields are populated and try again.';
            return null;
        }
        
        return null;
        
    }
    
    public List<SelectOption> getListOfObjects() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Please Select an Object--'));
        Schema.DescribeFieldResult fieldResult = Case_Template_Group__c.Object__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        } 
        
        return options;
    }
    
}