src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <businessProcess>Child</businessProcess>
        <label>Child</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <businessProcess>Parent</businessProcess>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Template__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Case_Template_Group__c</referenceTo>
        <relationshipLabel>Case Templates</relationshipLabel>
        <relationshipName>Case_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Case Template</label>
    <nameField>
        <label>Case Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template</pluralLabel>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <label>Child</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CoverCode__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thunderhead_Description__c</fullName>
        <label>Thunderhead Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CoverCode</label>
    <nameField>
        <label>CoverCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoverCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExcessCodeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>Ancillary_Excess_Description__c</fullName>
        <description>The description that should appear under the ancillary product in Thunderhead</description>
        <label>Ancillary Excess Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Description__c</fullName>
        <description>Is the description held on the system but not actually used for anything</description>
        <label>System Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ExcessCodeEmployee</label>
    <nameField>
        <label>ExcessCode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExcessCodesEmployee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExcessCodeEmployer__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web__c</fullName>
        <label>Web</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ExcessCodeEmployer</label>
    <nameField>
        <label>ExcessCodeEmployer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExcessCodesEmployer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Commercial_Analyst__c</fullName>
        <description>Derived from parent opportunity</description>
        <formula>IF(
NOT(ISBLANK(Opportunity__r.Commercial_Analyst__c)),
Opportunity__r.Commercial_Analyst__r.LastName &amp; &apos;, &apos; &amp; Opportunity__r.Commercial_Analyst__r.FirstName,
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Analyst</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity/Renewal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>The date that this record was superseded by publishing a newer version (this is a system field and can not be edited).</inlineHelpText>
        <label>Discard Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <description>A draft group (not yet implimented)</description>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Commercial_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This field is automatically calculated based on the start date + renewal months</inlineHelpText>
        <label>Effective Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Hospital Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extra</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Product</label>
    <nameField>
        <label>Requested Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>The number allocated to the section.</description>
        <externalId>true</externalId>
        <label>Section Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Cover_Code__c</fullName>
        <label>Cover Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Del Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Name_Web__c</fullName>
        <label>Product Name Web</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product_Link__c.object
<CustomObject>
    <description>Junction object between section and section product tables</description>
    <fields>
        <fullName>CoverCode__c</fullName>
        <formula>Product__r.Cover_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cover Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Section__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <formula>Section__r.Section_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Section Product Link</label>
    <nameField>
        <label>Section Product Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section Product Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/guTestUtil.cls
/////////////////////////////////////////////////////////////////
// Can be called by any test class to generate a usable cluster of data
// David Dawson
/////////////////////////////////////////////////////////////////
public class guTestUtil {
    
    public static void generateTestData(){
        
        Map<String, RecordType> rtMap = new Map<String, RecordType>();
        List<RecordType> rtList = new List<RecordType>([SELECT Id, sObjectType, Name FROM RecordType]);
        if(!rtList.isEmpty()){
            for(RecordType rt:rtList){
                rtMap.put(rt.Name + ' ' + rt.sObjectType, rt);
            }
        }
        
        Account broker = new Account(Name = 'Test Company', RecordTypeId = rtMap.get('Broker Account').Id);
        insert broker;
        
        Account client = new Account(Name = 'Test Client', RecordTypeId = rtMap.get('Prospect Account').Id, NumberOfEmployees = 200);
        insert client;
        
        Opportunity newOp = new Opportunity(Start_Date__c = system.Today(),StageName = 'New', CloseDate = system.Today().addDays(60), Name = 'Test Company Opportunity', AccountId = client.Id, Commercial_Analyst__c = UserInfo.getUserId(), RecordTypeId = rtMap.get('Opportunity Opportunity').Id);
        insert newOp;
        
        Group__c newGroup = new Group__c(Group_Number__c = '11111',Opportunity__c = newOp.Id, Name = 'Test Company Group', RecordTypeId = rtmap.get('Draft Group__c').Id);
        insert newGroup;
        
        Group__c newGroup2 = new Group__c(Group_Number__c = '11112',Opportunity__c = newOp.Id, Renewal_Date__c = system.TODAY(), Name = 'Test Company Group', RecordTypeId = rtmap.get('Group Group__c').Id);
        insert newGroup2;
        
        Section__c newSec = new Section__c(Group__c = newGroup.Id, Name = 'Test Company 0', Section_Number__c = '0', Date_On__c = system.Today().addDays(-10), Date_Closed__c = system.Today().addDays(100));
        insert newSec;
        
        list<CoverCode__c> newCCLst = new list<CoverCode__c>();
        
        CoverCode__c newCC1 = new CoverCode__c(Name='123', Sort_Order__c=1, Thunderhead_Description__c = 'TH desc', Type__c= 'A');
        newCCLst.add(newCC1);
        
        CoverCode__c newCC2 = new CoverCode__c(Name='124', Sort_Order__c=2, Thunderhead_Description__c = 'TH desc', Type__c= 'A');
        newCCLst.add(newCC2);
        
        CoverCode__c newCC3 = new CoverCode__c(Name='125', Sort_Order__c=3, Thunderhead_Description__c = 'TH desc', Type__c= 'A');
        newCCLst.add(newCC3);
        
        insert newCCLst; 
        
        ExcessCodeEmployee__c newEmpC = new ExcessCodeEmployee__c(Name ='1', Ancillary_Excess_Description__c='($250 single/$500 family excess)', System_Description__c='ANC 250/500 XS');
        insert newEmpC;
        
        ExcessCodeEmployer__c newEmprC = new ExcessCodeEmployer__c(name='401',Description__c='GROUP FED - HOSP 100/200',System__c='$100(S)/$200(F) Employer Excess ',Web__c='$100(S)/$200(F) Excess'); 
        insert newEmprC;
        
        Section_Product__c newSP = new Section_Product__c(Name = 'Test product', Cover_Code__c = '123 124', Product_Name_Web__c = 'Test product', Product_Type__c = 'Ancillary', Employee_Excess_Code_lkp__c = newEmpC.id, Employer_Excess_Code_lkp__c =  newEmprC.id );
        insert newSP;
        
        
        Section_Product_Link__c newSPL = new Section_Product_Link__c(Section__c = newSec.Id, Product__c = newSP.Id);
        insert newSPL;
        
        //Create some cases in case builder
        //Create some case templates
        Case_Template_Group__c ctg = new Case_Template_Group__c(Name = 'Groups', Subject__c = 'Group', Object__c = 'Opportunity;Renewal;Group;Section;Client Maintenance', ExternalId__c = 'GRP001');
        insert ctg;
        
        Case_Template__c ct0 = new Case_template__c(Name = 'Step 0', RecordTypeId = rtMap.get('Parent Case_Template__c').Id, Group__c = ctg.Id, Subject__c = 'Step 0', Code__c = 0, Fixed_SLA__c = FALSE);
        insert ct0;
        
        Case_Template__c ct1 = new Case_template__c(Name = 'Step 1', RecordTypeId = rtMap.get('Child Case_Template__c').Id, Group__c = ctg.Id, Subject__c = 'Step 1', Assigned_To__c = 'SSC', Code__c = 1, Fixed_Sla__c = TRUE, SLA1__c = 1);
        insert ct1;
        
        Case_Template__c ct2 = new Case_template__c(Name = 'Step 2', RecordTypeId = rtMap.get('Child Case_Template__c').Id, Group__c = ctg.Id, Subject__c = 'Step 1', Assigned_To__c = 'AM', Code__c = 2, Dependency__c = '1', Fixed_Sla__c = FALSE, SLA1__c = 1, SLA2__c = 3, Organisation_Size__c = 100);
        insert ct2;
        
    }
    
}