src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <businessProcess>Parent</businessProcess>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <label>Requested Product</label>
    <nameField>
        <label>Requested Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Status__c</fullName>
        <formula>Group__r.Is_Active__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Status of parent group</inlineHelpText>
        <label>Group Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>The number allocated to the section.</description>
        <externalId>true</externalId>
        <label>Section Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Del Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Amount_Funded__c</fullName>
        <label>Fixed Amount Funded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LHC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Del LHC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percentage_Funded__c</fullName>
        <label>Percentage Funded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>Unique code used to identify the product.</description>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ancillary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary &amp; Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary &amp; Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ancillary, Medical &amp; Hospital</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Code__c</fullName>
        <label>Rate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Del Rebate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Withdrawn_Date__c</fullName>
        <label>Del Withdrawn Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product_Link__c.object
<CustomObject>
    <description>Junction object between section and section product tables</description>
    <fields>
        <fullName>Base_or_Upgrade__c</fullName>
        <label>Base or Upgrade</label>
        <picklist>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Amount_Funded__c</fullName>
        <label>Fixed Amount Funded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Section__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Status__c</fullName>
        <formula>Section__r.Group__r.Is_Active__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Version__c</fullName>
        <formula>Section__r.Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Version</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LHC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LHC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percentage_Funded__c</fullName>
        <label>Percentage Funded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Broker_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Broker Code</label>
        <referenceTo>Broker_Code__c</referenceTo>
        <relationshipLabel>Section Product Links</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rebate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rebate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <formula>Section__r.Section_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Withdrawn_Date__c</fullName>
        <description>The date that the section product link is withdrawn (PLEASE NOTE that if a close date is specified, this takes precedence over Withdrawn date in calculating the status)</description>
        <inlineHelpText>The date that the section product link is withdrawn from</inlineHelpText>
        <label>Withdrawn Date</label>
        <type>Date</type>
    </fields>
    <label>Section Product Link</label>
    <nameField>
        <label>Section Product Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section Product Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sectionExtension.cls
public class sectionExtension {
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //
    //    Section Extension to permit additional functions on the SectionView page (replace standard UI
    //    The case list has been left here but has been removed from the VF page and a standard list used instead.
    //    We are however still using the custom product (Section_Product_Link__c) related list which gets all products that were linked to this section in the past but are not anymore
    //
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    private final Section__c section;
    //Custom Case list for related list
    public List<Case> cList {get;set;}
    //Map initially created for the Section Product Links to allow any manipulations before transfered to final list
    public Map<String, Section_Product_Link__c> splMap {get;set;}
    //List created to be viewed in custom related list on view page
    public List<Section_Product_Link__c> splList {get;set;}
    //Lists to store the locked fields and the synced fields
    public String lockedFields {get;set;}
    public String syncFields {get;set;}
    
    public String splMapMessage {get;set;}

    public sectionExtension (ApexPages.StandardController stdController) {
        //Add fields to record accessible by apex class (for SOQL query parameters mainly)
        if(!test.isRunningTest()){
            stdController.AddFields(new List<String>{'Group_Version__c'});
            stdController.AddFields(new List<String>{'Group_Number__c'});
            stdController.AddFields(new List<String>{'Section_Number__c'});
        }
        this.section = (Section__c)stdController.getRecord();
        
        //CASE RELATED LIST
        //Build a list of associated Cases
        cList = new List<Case>([SELECT Id, CaseNumber, Subject, Status, CreatedDate, Priority FROM Case WHERE Section__c =:section.Id ORDER BY CreatedDate]);
        
        //SECTION PRODUCT LINK RELATED LIST (PRODUCT HISTORY)
        //Create an instance of the Map and the List now to prevent null errors
        splMap = new Map<String, Section_Product_Link__c>();
        splList = new List<Section_Product_Link__c>();
        
        //We can only go through this process if the following fields are not null, otherwise the soql will fail
        if(section.Group_Version__c != null && section.Group_Number__c != null && section.Section_Number__c != null){
            //Build a set of product codes related to this record so that we can ensure these are not in the history related list
            Set<String> productCodes = new Set<String>();
           
            List<Section_Product_Link__c> splCheck = new List<Section_Product_Link__c>([SELECT Id, Product__r.Product_Code__c FROM Section_Product_Link__c WHERE Section__c =:section.Id]);
            
            for(Section_Product_Link__c spl:splCheck){
                productCodes.add(spl.Product__r.Product_Code__c);
            }
            
            //Get all section product links that were related to this psection in the past, and exclude any product codes that are currently active (done through SOQL)
             List<Section_Product_Link__c> splAR = new List<Section_Product_Link__c>([SELECT Id,Product__c,Product__r.Product_Code__c, Product__r.Rate_Code__c, Product__r.Product_Type__c,Section__c, Section__r.Group_Number__c, Section__r.Group_Version__c,Section__r.Group__c, Date_closed__c, Base_or_Upgrade__c, Section__r.Group_Status__c, Fixed_Amount_Funded__c, Percentage_Funded__c, Product_Broker_Code__c, Start_Date__c, Withdrawn_Date__c, LHC__c, Rebate__c, Product__r.Name FROM Section_Product_Link__c WHERE Section__r.Group_Number__c =:section.Group_Number__c AND Section_Number__c =:section.Section_Number__c AND Section__r.Group_Version__c <:section.Group_Version__c AND Product__r.Product_Code__c NOT IN :productCodes ORDER BY Section__r.Group_Version__c DESC ]);
            
            if(!splAR.isEmpty()){
                splMapMessage = 'No records to display';
                for(Section_Product_Link__c spl:splAR){
                    //The SOQL orders by Version number descending, so we only need the latest version
                    if(!splMap.containsKey(spl.Product__r.Product_Code__c)){
                        splMap.put(spl.Product__r.Product_Code__c, spl);
                    }
                }
                
                //After manipulation, add the final values to the list to be displayed on the page
                if(!splMap.isEmpty()){
                    for(Section_Product_Link__c spl:splMap.values()){
                        splList.add(spl);
                    }
                }
            }else{
                splMapMessage = 'No records to display';
            }
        }else{
            //If the fields are not all populated, let the user know that the data is not accessible
            splMapMessage = 'Data not accessible due to incomplete parent sections/groups';
        }
        
        //populate the locked fields list to pass to Javascript array
        List<String> lockTemp = new List<String>();
        List<Schema.FieldSetMember> LockedFieldSetMemberList =  Util.readFieldSet('WHICSFields','Section__c');
        for(Schema.FieldSetMember fieldSetMemberObj : LockedFieldSetMemberList){
            //lockedFields.add(fieldSetMemberObj.getFieldPath()); //api name
            lockTemp.add(fieldSetMemberObj.getLabel()); //label name
        }
        lockedFields = JSON.serialize(lockTemp);
        
        //populate the sync fields list to pass to Javascript array
        List<String> syncTemp = new List<String>();
        List<Schema.FieldSetMember> syncFieldSetMemberList =  Util.readFieldSet('SyncFields','Section__c');
        for(Schema.FieldSetMember fieldSetMemberObj : syncFieldSetMemberList){
            //syncFields.add(fieldSetMemberObj.getFieldPath()); //api name
            syncTemp.add(fieldSetMemberObj.getLabel()); //label name
        }
        syncFields = JSON.serialize(syncTemp);
        
    }
}