src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Template__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <picklist>
            <picklistValues>
                <fullName>Account Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wellness Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <description>Unique identifier for data migration</description>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Case_Template_Group__c</referenceTo>
        <relationshipLabel>Case Templates</relationshipLabel>
        <relationshipName>Case_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Template</label>
    <nameField>
        <label>Case Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Template_Group__c.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <description>Unique identifier for data migration</description>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Case Template Group</label>
    <nameField>
        <label>Case Template Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Template Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Copies</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Analyst__c</fullName>
        <description>Derived from parent opportunity</description>
        <formula>IF(
NOT(ISBLANK(Opportunity__r.Commercial_Analyst__c)),
Opportunity__r.Commercial_Analyst__r.LastName &amp; &apos;, &apos; &amp; Opportunity__r.Commercial_Analyst__r.FirstName,
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Analyst</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity/Renewal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the copy (calculated via the Group Version Number object which is updated via the Group Number)</description>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <label>Requested Product</label>
    <nameField>
        <label>Requested Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sections (Clone of)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>The number allocated to the section.</description>
        <externalId>true</externalId>
        <label>Section Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product__c.object
<CustomObject>
    <description>Products associated to Sections from WHICS</description>
    <fields>
        <fullName>Clone_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clone of</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipName>Section_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Del Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Del Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name System (Short)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Product_Link__c.object
<CustomObject>
    <description>Junction object between section and section product tables</description>
    <fields>
        <fullName>Date_closed__c</fullName>
        <label>Date closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Section__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Version__c</fullName>
        <formula>Section__r.Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Version</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Section_Product__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <formula>Section__r.Section_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Section_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Section__r.Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section Product Link</label>
    <nameField>
        <label>Section Product Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section Product Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/guSFDCTestClass.cls
/////////////////////////////////////////////////////////////////
// Test class constructed for end-to-end process (go live r1)
// David Dawson
/////////////////////////////////////////////////////////////////
@isTest
private class guSFDCTestClass {
    
    static testMethod void opportunityProcess() {
        
        //generate data
        guTestUtil.generateTestData();
        
        Account client = [SELECT Id, Name, RecordTypeId, RecordType.Name, NumberOfEmployees FROM Account WHERE Name = 'Test Client' LIMIT 1];
        Opportunity newOp = [SELECT Start_Date__c, StageName, CloseDate, Name, AccountId, Commercial_Analyst__c, RecordTypeId FROM Opportunity WHERE Name = 'Test Company Opportunity' LIMIT 1];
        Group__c newGroup = [SELECT Group_Number__c, Opportunity__c, Name, RecordTypeId, Version__c,Clone_Of__c, Clone_Of__r.Is_Active__c, RecordType.Name FROM Group__c WHERE Group_Number__c = '11111' LIMIT 1];
        Section__c newSec = [SELECT Group__c, Name, Section_Number__c, Date_On__c, Date_Closed__c, Group_Version__c, Group_Number__c FROM Section__c WHERE Group_Number__c = :newGroup.Group_Number__c AND Section_Number__c = '0' LIMIT 1];
        Section_Product_Link__c newSPL = [SELECT Section__c, Product__c FROM Section_Product_Link__c LIMIT 1];
        
        List<Case_Template_Group__c> ctgList = new List<Case_Template_Group__c>([SELECT Name, Subject__c, Object__c, ExternalId__c FROM Case_Template_Group__c]);
        Case_Template_Group__c ctg = ctgList[0];
        
        List<Case_Template__c> ctList = new List<Case_Template__c>([SELECT Name, RecordTypeId, Group__c, Subject__c, Assigned_To__c, Code__c, Fixed_Sla__c, Dependency__c, SLA1__c, SLA2__c, Organisation_Size__c FROM Case_Template__c]);
        Case_Template__c ct0 = ctList[0];
        Case_Template__c ct1 = ctList[1];
        Case_Template__c ct2 = ctList[2];
        
        Map<String, RecordType> rtMap = new Map<String, RecordType>();
        List<RecordType> rtList = new List<RecordType>([SELECT Id, sObjectType, Name FROM RecordType]);
        if(!rtList.isEmpty()){
            for(RecordType rt:rtList){
                rtMap.put(rt.Name + ' ' + rt.sObjectType, rt);
            }
        }
        
        Test.Starttest();
        
            //View Account
            ApexPages.StandardController stdaController = new ApexPages.StandardController(client);
            accountExtension aE = new accountExtension(stdaController);
            
            //View Opportunity
            ApexPages.StandardController stdopController = new ApexPages.StandardController(newOp);
            opportunityExtension oE = new opportunityExtension(stdopController);
            
            //View Group (only gets 69% coverage, need to fire again post Client Maintenance or Renewal process test)
            ApexPages.StandardController stdgController = new ApexPages.StandardController(newGroup);
            groupExtension gE = new groupExtension(stdgController);
        	gE.showMessage();
            
            //View Section
            ApexPages.StandardController stdsecController = new ApexPages.StandardController(newSec);
            sectionExtension secE = new sectionExtension(stdsecController);
        
        //Edit a field in Section that will fire WHICS calidation (locked fields)
        //Section
        newSec.Member__c = 200;
        update newSec;
		
        //Section Product Link
        newSPL.LHC__c = TRUE;
        update newSPL;
        
        //Go to case landing page and select the insert opportunity above
        Case c = new Case();
        ApexPages.StandardController caseController = new ApexPages.StandardController(c);  
        caseTemplateLanding ctl = new caseTemplateLanding(caseController);
        //call picklist items
        ctl.getListOfObjects();
        
        //Search for each object
            //Search for Opportunity
            ctl.objectName = 'Opportunity';
            ctl.searchCriteria = 'test';
            ctl.searchSF();
        
            //Search for Group
            ctl.objectName = 'Group';
            ctl.searchCriteria = 'test';
            ctl.searchSF();
        
            //Search for Section
            ctl.objectName = 'Section';
            ctl.searchCriteria = 'test';
            ctl.searchSF();
        
            //Search for Client
            ctl.objectName = 'Client';
            ctl.searchCriteria = 'test';
            ctl.searchSF();
        
        //Lets open the Case Builder page
            //Open an opportunity record
            Test.setCurrentPageReference(new PageReference('Page.caseTemplateBuilder'));
            System.currentPageReference().getParameters().put('oid', newOp.Id);
            System.currentPageReference().getParameters().put('aid', client.Id);
            System.currentPageReference().getParameters().put('sObjectType', 'Opportunity');
            caseTemplateBuilder ctbOp = new caseTemplateBuilder();
        
            ctbOp.selectedTemplate = ctg.Id;
            ctbOp.findCaseTemplates();
            ctbOp.submit();
        
            //Open an account record
            Test.setCurrentPageReference(new PageReference('Page.caseTemplateBuilder'));
            System.currentPageReference().getParameters().put('oid', client.Id);
            System.currentPageReference().getParameters().put('aid', client.Id);
            System.currentPageReference().getParameters().put('sObjectType', 'Client');
            caseTemplateBuilder ctbAc = new caseTemplateBuilder();
        
            ctbAc.selectedTemplate = ctg.Id;
            ctbAc.findCaseTemplates();
            ctbAc.submit();
        
            //Open a group record
            Test.setCurrentPageReference(new PageReference('Page.caseTemplateBuilder'));
            System.currentPageReference().getParameters().put('oid', newGroup.Id);
            System.currentPageReference().getParameters().put('aid', client.Id);
            System.currentPageReference().getParameters().put('sObjectType', 'Group');
            caseTemplateBuilder ctbGr = new caseTemplateBuilder();
        
            ctbGr.selectedTemplate = ctg.Id;
            ctbGr.findCaseTemplates();
            ctbGr.submit();
        
            //Open a section record
            Test.setCurrentPageReference(new PageReference('Page.caseTemplateBuilder'));
            System.currentPageReference().getParameters().put('oid', newSec.Id);
            System.currentPageReference().getParameters().put('aid', client.Id);
            System.currentPageReference().getParameters().put('sObjectType', 'Section');
            caseTemplateBuilder ctbSec = new caseTemplateBuilder();
        
            ctbSec.selectedTemplate = ctg.Id;
            ctbSec.findCaseTemplates();
            ctbSec.submit();
            ctbSec.getGroups();
            ctbSec.getListOfObjects();
        
        //insert some cases that meet the case scheduler requirements
        List<Case> caseList = new List<Case>();
        caseList.add(new Case(Estimated_Close_Date__c = system.Today().addDays(-1)));
        caseList.add(new Case(Estimated_Close_Date__c = system.Today()));
        caseList.add(new Case(Estimated_Close_Date__c = system.Today().addDays(1)));
        insert caseList;
        
        //Run the case scheduler
        Datetime dtcase = Datetime.now().addMinutes(1);
        String CRON_EXPcase = '0 '+ dtcase.minute() + ' * ' + dtcase.day() + ' ' + dtcase.month() + ' ? ' + dtcase.year();
        String jobIdcase = System.schedule('Case_Heading', CRON_EXPcase, new caseSLACheckSchedule() ); 
        
        //Close some cases to check that the job trigger is working
        List<Case> cList = new List<Case>([SELECT Id, Status, ClosedDate FROM Case WHERE Status = 'Task ready to start']);
        for(Case ca:cList){
            ca.Status = 'Task completed';
        }
        update cList;
        
        List<Case> c2List = new List<Case>([SELECT Id, Status, ClosedDate FROM Case WHERE Status = 'Task ready to start']);
        for(Case ca2:c2List){
            ca2.Status = 'Task completed';
        }
        update c2List;
    
        Test.Stoptest();

    }
    
    static testMethod void  SectionCloseDateISTodayTest(){
        //generate data
        guTestUtil.generateTestData();
        SectionCloseDateISToday sobj = new SectionCloseDateISToday();
        Test.Starttest();
        	sobj.execute(null);
        Test.Stoptest();   
    }
    
    static testMethod void  ProductHandlerTest(){
        //generate data
        boolean bErroGenCvrCode = false;
        boolean bErroGenCvrCode2 = false;
        boolean bErroGenCvrCode3 = false;
        guTestUtil.generateTestData();
        list<Section_Product__c> newSPLst = [select id , Cover_Code__c from Section_Product__c limit 200 ];
        Test.Starttest();
        Section_Product__c newSP = newSPLst[0];
        newSP.Cover_Code__c = '123 124 125';
        update newSP;
        
        newSP.Cover_Code__c = '123 124 125 3dffsafa';
        try {
          update newSP;  
        }catch(system.DmlException DMLe){
            bErroGenCvrCode = true;
        }
        
        newSP.Cover_Code__c = '123 124 999';
        try {
          update newSP;  
        }catch(system.DmlException DMLe){
            bErroGenCvrCode2 = true;
        }
        
        
        newSP.Cover_Code__c = '';
        try {
          update newSP;  
        }catch(system.DmlException DMLe){
            bErroGenCvrCode3 = true;
        }
        Test.Stoptest(); 
        
        system.assertEquals(bErroGenCvrCode , true);
        system.assertEquals(bErroGenCvrCode2 , true);
        system.assertEquals(bErroGenCvrCode3 , false); 
        
    }
    
    static testMethod void cloningProcess() {
        
        //generate data
        guTestUtil.generateTestData();
        
        Account client = [SELECT Id, Name, RecordTypeId, RecordType.Name, NumberOfEmployees FROM Account WHERE Name = 'Test Client' LIMIT 1];
        Opportunity newOp = [SELECT Start_Date__c, StageName, CloseDate, Name, AccountId, Commercial_Analyst__c, RecordTypeId FROM Opportunity WHERE Name = 'Test Company Opportunity' LIMIT 1];
        Group__c newGroup = [SELECT Group_Number__c, Opportunity__c, Name, RecordTypeId FROM Group__c WHERE Group_Number__c = '11111' LIMIT 1];
        Section__c newSec = [SELECT Group__c, Name, Section_Number__c, Date_On__c, Date_Closed__c, Group_Version__c, Group_Number__c FROM Section__c WHERE Group_Number__c = :newGroup.Group_Number__c AND Section_Number__c = '0' LIMIT 1];
        
        List<Case_Template_Group__c> ctgList = new List<Case_Template_Group__c>([SELECT Name, Subject__c, Object__c, ExternalId__c FROM Case_Template_Group__c]);
        Case_Template_Group__c ctg = ctgList[0];
        
        List<Case_Template__c> ctList = new List<Case_Template__c>([SELECT Name, RecordTypeId, Group__c, Subject__c, Assigned_To__c, Code__c, Fixed_Sla__c, Dependency__c, SLA1__c, SLA2__c, Organisation_Size__c FROM Case_Template__c]);
        Case_Template__c ct0 = ctList[0];
        Case_Template__c ct1 = ctList[1];
        Case_Template__c ct2 = ctList[2];
        
        Map<String, RecordType> rtMap = new Map<String, RecordType>();
        List<RecordType> rtList = new List<RecordType>([SELECT Id, sObjectType, Name FROM RecordType]);
        if(!rtList.isEmpty()){
            for(RecordType rt:rtList){
                rtMap.put(rt.Name + ' ' + rt.sObjectType, rt);
            }
        }
        
        Test.Starttest();
        
        
        //Lets update the opportunity record with the final values required and publish it
        //Update the Opportunity record 
        newOp.StageName = 'Closed Won';
        newOp.CloseDate = system.Today();
        newOp.Confirmed_funding_model__c = 'Some text goes here';
        newOp.Confirmed_Launch_plans__c = 'Some text goes here';
        newOp.Result_Comments__c = 'Some text goes here';
        update newOp;
        
        //Update the group record
        newGroup.Start_Date__c = system.Today();
        newGroup.RecordTypeId = rtMap.get('Group Group__c').Id;
        update newGroup;
        
        //Call the publish function for Group (not in opportunity, needs to be in Client Maintenance publish)
        //String retireResult = renewalManual.retireGroup(newGroup, newGroup.Start_Date__c);    
    
    	//Create a Client Maintenance record
        Id cmID = renewalManual.processManually(String.valueOf(newGroup.Id), 'with', 'Client Maintenance', 'Group__c');
    
    	//Clone Section
        Id nsID = renewalManual.processManually(String.valueOf(newSec.Id), 'with', 'Client Maintenance', 'Section__c');
    
    	//Lets get the new CM group
        Group__c CMGroup = [SELECT Id, Name, Group_Number__c, Version__c FROM Group__c WHERE Id=:cmID];
    
    	//View Group
        ApexPages.StandardController stdg2Controller = new ApexPages.StandardController(CMGroup);
        Test.setCurrentPageReference(new PageReference('Page.groupView'));
        System.currentPageReference().getParameters().put('id', CMGroup.Id);
        groupExtension gE2 = new groupExtension(stdg2Controller);
    
    	//Dummy publish initiation
    	publishWizardExtension pWE = new publishWizardExtension(stdg2Controller);
        //Activate date null rule
        pWE.publishGroup();
        //add date and fire again
        pWE.publishDate = system.TODAY();
        pWE.publishGroup();
    
    	//Lets publish this new Group
        //Discard old groups first
        String closeResult = renewalManual.retireGroup(newGroup, system.Today().addDays(-2));
    
        //publish new record
        CMGroup.RecordTypeId = rtMap.get('Group Group__c').Id;
        CMGroup.Start_Date__c = system.Today().addDays(-2);
        update CMGroup;
    
    	//Call the opportunity Tab from the 3 different perspectives
        //Opportunity
        Test.setCurrentPageReference(new PageReference('Page.opportunityTab'));
        opportunityTab oTabO = new opportunityTab();
        otabO.pageName = 'Opportunity';
        otabO.getViews();
    
        //Client Maintenance
        Test.setCurrentPageReference(new PageReference('Page.maintenanceTab'));
        opportunityTab oTabCM = new opportunityTab();
        otabCM.pageName = 'Client Maintenance';
        otabCM.getViews();
    
        //Renewal
        Test.setCurrentPageReference(new PageReference('Page.renewalTab'));
        opportunityTab oTabR = new opportunityTab();
        otabR.pageName = 'Renewal';
        otabR.getViews();
    
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        String jobId = System.schedule('Sample_Heading', CRON_EXP, new groupRecordTypeSchedule() ); 
    
        //Run the renewal scheduler
        Datetime dtren = Datetime.now().addMinutes(1);
        String CRON_EXPren = '0 '+ dtren.minute() + ' * ' + dtren.day() + ' ' + dtren.month() + ' ? ' + dtren.year();
        String jobIdren = System.schedule('Renewal_Heading', CRON_EXPren, new renewalScheduler() ); 
        
        Test.Stoptest();
        
    }
  
}