src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Closed_on__c</fullName>
        <inlineHelpText>This is the date that the record was closed. If this date is populated and is less then todays date (or the same date) then the record will be closed.</inlineHelpText>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field (system) to distinguish whether the record has been edited using the publish wizard. Tells the system to change the record type to active.</description>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Join_Online_available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Group has OMS</description>
        <label>OMS Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>The date that this record was superseded by publishing a newer version (this is a system field and can not be edited).</inlineHelpText>
        <label>Discard Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the copy (calculated via the Group Version Number object which is updated via the Group Number)</description>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Join_Online_available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Set to True when the customer can join online.</description>
        <label>Join Online available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMS_Activation_Date__c</fullName>
        <description>Indicates date OMS was activated</description>
        <inlineHelpText>Indicates date OMS was activated</inlineHelpText>
        <label>OMS Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OMS_Disabled_Date__c</fullName>
        <description>Indicates date OMS was disabled</description>
        <inlineHelpText>Indicates date OMS was disabled</inlineHelpText>
        <label>OMS Disabled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OMS_status__c</fullName>
        <description>Indicates if OMS is active for the Section</description>
        <inlineHelpText>Indicates if OMS is active for the Section</inlineHelpText>
        <label>OMS status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>The number allocated to the section.</description>
        <externalId>true</externalId>
        <label>Section Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SharedKey__c</fullName>
        <formula>Group__r.Group_Number__c &amp; &quot;s&quot; &amp; Section_Number__c</formula>
        <label>Shared Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
Group__r.Is_Active__c = &apos;Draft&apos;, &apos;Draft&apos;,
IF(
Group__r.Is_Active__c = &apos;Pending&apos;, &apos;Pending&apos;,
IF(
Date_Closed__c &lt;= TODAY(), &apos;Closed&apos;, Group__r.Is_Active__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sectionTriggerHandler.cls
public class sectionTriggerHandler{
    
    //Syncs group fields across other versions (as dictated in relevant field set)
    public Void syncSectionFields(){
        //Check if the trigger is on or off
        if(Label.GRP_SyncFields.toUpperCase() == 'TRUE'){
        
            guUtil utility = new guUtil();
			utility.syncFields('Section__c', 'SharedKey__c, Version__c', 'Version__c', 'SharedKey__c');
            
        }
    }
    
    //WHICS Fields validation
    public Void whicsValidation(){

        //exclude records if they have come from the publish wizard
        list<Section__c> newSectLst = (List<Section__c>)Trigger.NEW;
        Boolean isPublishWizard = newSectLst[0].IsPublishWizard__c;
        

        if(Label.WHICS_Val.toUpperCase() == 'TRUE' && isPublishWizard == false){
            guUtil utility = new guUtil();
			utility.lockedFields('Section__c', 'Status__c');
        }else{
            //reset the publish wizard token for all records
            for(Section__c s :(List<Section__c>)Trigger.NEW){
                s.IsPublishWizard__c = false;
            }
        }
    }
    
    public void UpdateOMSActivationDtOMSDisableDtOMSStatus(){
        list<Section__c> newSectLst = (List<Section__c>)Trigger.NEW;
        // list<Section__c> oldSectMap = (List<Section__c>)Trigger.oldMap ;
        // 
        list<id> GrpIDLst = new list<id>();
        for(Section__c secGrp : newSectLst){
            GrpIDLst.add(secGrp.group__c);
        }
        
        list<group__c> secGrpLst = [select id, Is_Active__c,Start_Date__c ,RecordType.Name, Renewal_Date__c,Closed_on__c from group__c where id in :GrpIDLst ];
        map<id,group__c> secGrpMap= new map<id,group__c>();
        for(group__c grpidSec : secGrpLst ){
            secGrpMap.put(grpidSec.id,grpidSec);
        }
        //boolean bUpdtVal ;
        for(Section__c Sect:  newSectLst){
            if(!(Sect.Section_Number__c == '0' || 	Sect.Section_Number__c == '300')){
              	Sect.OMS_status__c = Sect.OMS_Activation_Date__c == null && Sect.OMS_Disabled_Date__c == null ? 'Disabled' : Sect.OMS_status__c; 
           	 	Sect.OMS_status__c = Sect.OMS_Activation_Date__c <= date.today() && Sect.OMS_Disabled_Date__c == null ? 'Active' : Sect.OMS_status__c; 
             	Sect.OMS_status__c = Sect.OMS_Activation_Date__c <= date.today() && Sect.OMS_Disabled_Date__c >  date.today() ? 'Active'  : Sect.OMS_status__c;
             	Sect.OMS_status__c = Sect.OMS_Activation_Date__c > date.today() && Sect.OMS_Disabled_Date__c == null ? 'Disabled' : Sect.OMS_status__c;  
             	Sect.OMS_status__c = Sect.OMS_Activation_Date__c > date.today() && Sect.OMS_Disabled_Date__c  > date.today() ? 'Disabled' : Sect.OMS_status__c;
            
             	Sect.OMS_status__c = Sect.OMS_Disabled_Date__c <= date.today()  ? 'Disabled' : Sect.OMS_status__c;  
            }
            
            
        }          
    }
    
    
	public  void UpdateOMSAvailableFieldInGrp(){
		set<Id> GrpIdActiveSet = new Set<Id>(); 
		set<Id> GrpIdDisabledSet = new Set<Id>(); 
       // system.debug('$(List<Section__c>)Trigger.NEW count=' + (List<Section__c>)Trigger.NEW.size());
		 for(Section__c s :(List<Section__c>)Trigger.NEW){
             if(!(s.Section_Number__c == '0' || 	s.Section_Number__c == '300') ){
             	if(s.OMS_status__c == 'Active' && s.group__c != null ){
                    GrpIdActiveSet.add(s.group__c);
                    if(GrpIdDisabledSet.contains(s.group__c)){
                        GrpIdDisabledSet.remove(s.group__c);
                    }
                } else {
                    if(!GrpIdActiveSet.contains(s.group__c)){
                        GrpIdDisabledSet.Add(s.group__c);
                    }
                }    
             }
             
		 }
        
		system.debug('$GrpIdActiveSet = ' + GrpIdActiveSet  ); 
		 LIST<group__c> updGrpLst = [select id, Join_Online_available__c from group__c where id in :GrpIdActiveSet or id in :GrpIdDisabledSet]; 
		 LIST<group__c> updChangeGrpLst = new LIST<group__c>();
        
		 for(Group__c ugrp : updGrpLst){
		 	if(GrpIdActiveSet.contains(ugrp.id)){
				if(ugrp.Join_Online_available__c != true){
					ugrp.Join_Online_available__c = true;
					updChangeGrpLst.add(ugrp);
				}
			} else {
				if(ugrp.Join_Online_available__c != false){
					ugrp.Join_Online_available__c = false;
					updChangeGrpLst.add(ugrp);
				}
			}
		 }
         system.debug('$updChangeGrpLst count=' + updChangeGrpLst.size());
		 update updChangeGrpLst;
	}
	
	//Set External Id
	public void setExternalId(){
		for(Section__c s :(List<Section__c>)Trigger.NEW){
			if(s.Group_Number__c != null && s.Version__c != null && s.Section_Number__c != null){
				s.External_ID__c = guUtil.getSectionExtId(s.Group_Number__c, s.Section_Number__c, String.valueOf(s.Version__c.setScale(0)));
			}	
		}
	}
}