src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Closed_on__c</fullName>
        <inlineHelpText>This is the date that the record was closed. If this date is populated and is less then todays date (or the same date) then the record will be closed.</inlineHelpText>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field (system) to distinguish whether the record has been edited using the publish wizard. Tells the system to change the record type to active.</description>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>The date that this record was superseded by publishing a newer version (this is a system field and can not be edited).</inlineHelpText>
        <label>Discard Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/groupRecordTypeSchedule.cls
global class groupRecordTypeSchedule Implements Schedulable{
    
    global void execute(SchedulableContext sc){
        List<Group__c> groupList = [select Id, 
                                    Name, 
                                    IsPublishWizard__c,
                                    Closed_on__c,
                                    Start_Date__c,
                                    Group_Number__c 
                                    from Group__c 
                                    where 
                                    (Start_Date__c = TODAY) 
                                    or (Start_Date__c = TODAY and Closed_on__c <= TODAY)
                                    or (Renewal_Date__c = TODAY)];
        if(!groupList.isEmpty()){
            for (Group__c groupRec : groupList){
                groupRec.IsPublishWizard__c = true;//Set the flag so that these records are picked up by the Group trigger and correct record type is set.                
            }
            update groupList;
        }
    }
    
}