src/objects/Group__c.object
<CustomObject>
    <description>Groups from WHICS</description>
    <fields>
        <fullName>Closed_on__c</fullName>
        <inlineHelpText>This is the date that the record was closed. If this date is populated and is less then todays date (or the same date) then the record will be closed.</inlineHelpText>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_Not_Calculate_Renewal_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Prevent the system from calculating the renewal date automatically (this can be used in special circumstances where the renewal date needs to be manually set to a date that does not meet standard procedural requirements e.g. can not wait 12 months)</inlineHelpText>
        <label>Do Not Calculate Renewal Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number from WHICS</description>
        <inlineHelpText>This field needs to be 5 digits long and all numeric</inlineHelpText>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field (system) to distinguish whether the record has been edited using the publish wizard. Tells the system to change the record type to active.</description>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF( 
Start_Date__c &gt; TODAY(), &apos;Pending&apos;, 
IF(
RecordType.Name == &apos;Draft&apos;, &apos;Draft&apos;,
IF(
AND(
Renewal_Date__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Discarded&apos;,
IF(
AND(
Closed_on__c &lt;= TODAY(),
RecordType.Name == &apos;Replaced&apos;), &apos;Closed&apos;, &apos;Active&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity/Renewal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Real_Renewal_Date__c</fullName>
        <description>Publish Date + 12 months (calculated by trigger)</description>
        <inlineHelpText>This is the date that the group is due for renewal.</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>The date that this record was superseded by publishing a newer version (this is a system field and can not be edited).</inlineHelpText>
        <label>Discard Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Frequency__c</fullName>
        <inlineHelpText>This is the number of months before the next renewal.</inlineHelpText>
        <label>Renewal Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Processed_Time__c</fullName>
        <description>When the renewal was created (either manually or automatically). Once this field is populated, the scheduler will not clone it automatically</description>
        <inlineHelpText>When the renewal was created (either manually or automatically). Once this field is populated, the scheduler will not clone it automatically</inlineHelpText>
        <label>Renewal Processed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal_Trigger_Date__c</fullName>
        <description>This is the date that the system will create a new renewal (if one has not been created manually already).</description>
        <inlineHelpText>This is the date that the system will create a new renewal (if one has not been created manually already).</inlineHelpText>
        <label>Renewal Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the copy (calculated via the Group Version Number object which is updated via the Group Number)</description>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name Brochure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <description>A draft group (not yet implimented)</description>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <description>Standard record type</description>
        <label>Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Replaced</fullName>
        <active>true</active>
        <description>When a group is superceded</description>
        <label>Replaced</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group_Version_Number__c.object
<CustomObject>
    <description>Keeping a version number of each group</description>
    <fields>
        <fullName>Group_Number__c</fullName>
        <externalId>true</externalId>
        <label>Group Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <description>The current and latest version number (updated via trigger)</description>
        <label>Version Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group Version Number</label>
    <nameField>
        <displayFormat>GRPV{000000}</displayFormat>
        <label>Group Version Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Version Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This field is automatically calculated based on the start date + renewal months</inlineHelpText>
        <label>Effective Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For won opportunity, start date</description>
        <inlineHelpText>For won opportunity, start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Client_Maintenance</fullName>
        <active>true</active>
        <businessProcess>Client Maintenance</businessProcess>
        <label>Client Maintenance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal</businessProcess>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Group__r.Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMS_Disabled_Date__c</fullName>
        <description>Indicates date OMS was disabled</description>
        <inlineHelpText>Indicates date OMS was disabled</inlineHelpText>
        <label>OMS Disabled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OMS_status__c</fullName>
        <description>Indicates if OMS is active for the Section</description>
        <inlineHelpText>Indicates if OMS is active for the Section</inlineHelpText>
        <label>OMS status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>The number allocated to the section.</description>
        <externalId>true</externalId>
        <label>Section Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Group__r.Version__c</formula>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/groupTriggerHandler.cls
/////////////////////////////////
// Handler Class for Group Object
// Created by David Dawson
/////////////////////////////////

public class groupTriggerHandler{
    
    //Ensures all groups being saves are given the correct record type
    public void recordTypeCheck(){
        
        Map<String, RecordType> rtMap = new Map<String, RecordType>();
        List<RecordType> rtList = new List<RecordType>([SELECT Id, Name FROM RecordType WHERE sObjectType = 'Group__c' AND (Name = 'Group' OR Name = 'Replaced' OR Name = 'Draft')]);
        if(!rtList.isEmpty()){
            
            for(RecordType rt:rtList){
                rtMap.put(rt.Name, rt);
            }
            
            for(Group__c g :(List<Group__c>)Trigger.NEW){
				System.debug(g.Start_Date__c);
				if(g.IsPublishWizard__c && ((g.Renewal_Date__c != null && g.Renewal_Date__c <= system.TODAY()) || (g.Closed_On__c != null && g.Closed_On__c <= system.TODAY()))){
                    g.RecordTypeId = rtMap.get('Replaced').Id;
                }else if(g.Start_Date__c <= System.today() && g.IsPublishWizard__c){
					g.RecordTypeId = rtMap.get('Group').Id;
				}else if((g.Start_Date__c == null || g.Start_Date__c > system.TODAY()) && g.RecordTypeId != rtMap.get('Draft').Id){
                    g.RecordTypeId = rtMap.get('Draft').Id;
                }
            }

            publishWizard();  
        }
    }
    
    /**
     * @author         
     * @description     Ensures all of the groups have correct renewal dates calculated for them.
     * @history         Updated - 30/11/2016 - K.Vegerano (kristian.vegerano@australianunity.com)
     *                  - GVT-303: Renewal Date Calculation - new condition - enable auto renewal calculation on pending and active groups
     */
    public Void renewalDates(){
        //Collect group Ids
        Set<Id> renewalDates = new Set<Id>();
        for(Group__c g :(List<Group__c>)Trigger.NEW){
            if(g.Id != null){
                renewalDates.add(g.Id);
            }
        }
        
        //Retrieve Opportunity Record Type Name
        Map<Id, Group__c> groupMap = new Map<Id, Group__c>();
        for(Group__c loopGroup : [SELECT Id, Opportunity__r.RecordType.Name, Opportunity__r.RecordType.DeveloperName FROM Group__c WHERE Id IN :renewalDates]){
            groupMap.put(loopGroup.Id, loopGroup);
        }
        
        //Calculation of Renewal Date process
        for(Group__c g :(List<Group__c>)Trigger.NEW){
            //Check if the group has Id (trigger is on update)
            if(groupMap.containsKey(g.Id)){
                if(groupMap.get(g.Id).Opportunity__r.RecordType.DeveloperName != 'Client_Maintenance' && g.Start_Date__c != null && g.Do_Not_Calculate_Renewal_Date__c == false){
                    //GVT-303 - 25/11/2016 - recalculation based with renewal frequency
                    if(g.Renewal_Frequency__c != null){
                        g.Real_Renewal_Date__c = g.Start_Date__c.addMonths(Integer.valueOf(g.Renewal_Frequency__c));
                    }else{
                        g.Real_Renewal_Date__c = g.Start_Date__c.addYears(1);
                    }
                    g.Renewal_Trigger_Date__c = g.Real_Renewal_Date__c.addMonths(-4);
                }   
                
                //Calculate Renewal Trigger Date 4 months prior to the renewal date
                if(Trigger.OLDMAP != null){
                    if(Trigger.OLDMAP.containsKey(g.Id)){
                        if(((Group__c)Trigger.OLDMAP.get(g.Id)).Real_Renewal_Date__c != g.Real_Renewal_Date__c){
                            if(g.Real_Renewal_Date__c != null){
                                g.Renewal_Trigger_Date__c = g.Real_Renewal_Date__c.addMonths(-4);
                            }else{
                                g.Renewal_Trigger_Date__c = null;
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * @author          K.Vegerano (kristian.vegerano@australianunity.com)
     * @description     Reset the Renewal_Processed_Time__c field on active group when there are no draft or pending groups.
     * @history         Created - 14/12/2016 - K.Vegerano (kristian.vegerano@australianunity.com)
     *                  - GVT-303: Renewal Date Calculation - Enabled the renewal scheduler to pick up active group with created renewal but later on discarded
     */
    public void resetRenewalProcessTime(List<Group__c> groupList){
        
    }
    
    //Syncs group fields across other versions (as dictated in relevant field set)
    public Void syncGroupFields(){
        //Check if the trigger is on or off
        if(Label.GRP_SyncFields.toUpperCase() == 'TRUE'){
        	
			guUtil utility = new guUtil();
			utility.syncFields('Group__c', null, 'Version__c', 'Group_Number__c');

        }
    }
    
    //group versioning
    public Void versioningGroups(){
        Set<String> versionNumbers = new Set<String>();
        Map<String, Group_Version_Number__c> gvnMap = new Map<String, Group_Version_Number__c>();

        for(Group__c g :(List<Group__c>)Trigger.NEW){
            if(g.Group_Number__c != null && g.Version__c == null){
                versionNumbers.add(g.Group_Number__c);
            }
        }
        
        if(!versionNumbers.isEmpty()){
    
            List<Group_Version_Number__c> gvnList = new List<Group_Version_Number__c>([SELECT Id, Version_Number__c, Group_Number__c FROM Group_Version_Number__c WHERE Group_Number__c IN:versionNumbers]);
            if(!gvnList.isEmpty()){
                for(Group_Version_Number__c gvn:gvnList){
                    gvnMap.put(gvn.Group_Number__c, gvn);
                }
            }
            
            for(String vn:versionNumbers){
                if(!gvnMap.containsKey(vn)){
                    gvnMap.put(vn, new Group_Version_Number__c(Group_Number__c = vn, Version_Number__c = 0));
                }
            }
            
            for(Group__c g :(List<Group__c>)Trigger.NEW){
                if(gvnMap.containsKey(g.Group_Number__c)){
                    gvnMap.get(g.Group_Number__c).Version_Number__c = gvnMap.get(g.Group_Number__c).Version_Number__c + 1;
                    g.Version__c = gvnMap.get(g.Group_Number__c).Version_Number__c;
                }
            }
            
            try{
                upsert gvnMap.values();
            }catch(Exception e){
                system.debug('Could not update version map ' + gvnMap);
            }
            
        }
    }
    
    //WHICS Fields validation
    public Void whicsValidation(){
        
        if(Label.WHICS_Val.toUpperCase() == 'TRUE'){
        	guUtil utility = new guUtil();
			utility.lockedFields('Group__c', 'Is_Active__c');
        }
        
    }
    
    //Change record type of records published through the publish wizard
    public Void publishWizard(){

        for(Group__c g :(List<Group__c>)Trigger.NEW){
            if(g.IsPublishWizard__c){
                g.IsPublishWizard__c = FALSE;
            }
        }
        
    }
    
    //Join Online Mass deactivation when group is closed 
    public void MassDeactivateSectionOnGrpClose(){
        map<id,Group__c> mGrpCls = new map<id,Group__c>();
        for(Group__c g :(List<Group__c>)Trigger.NEW){
            if(g.Is_Active__c == 'Closed'){
                mGrpCls.put(g.id, g);
            }
        }
        list<section__c> SecLst = [select id ,OMS_status__c,OMS_Disabled_Date__c from section__c where 	Group__c in : mGrpCls.keySet()  and  Section_Number__c not in ('0','300') and OMS_status__c != 'Disabled'    ];
        for(section__c sec : SecLst ){
            sec.OMS_status__c = 'Disabled';
            sec.OMS_Disabled_Date__c = date.today();
        }
        update SecLst;
    }
    
}