src/objects/Section__c.object
<CustomObject>
    <description>Sections from WHICS</description>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OMS_Activation_Date__c</fullName>
        <description>Indicates date OMS was activated</description>
        <inlineHelpText>Indicates date OMS was activated</inlineHelpText>
        <label>OMS Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OMS_Disabled_Date__c</fullName>
        <description>Indicates date OMS was disabled</description>
        <inlineHelpText>Indicates date OMS was disabled</inlineHelpText>
        <label>OMS Disabled Date</label>
        <type>Date</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SectionCloseDateISToday.cls
// Scheduler to set oms status if OMS dates are today 
global class SectionCloseDateISToday implements Schedulable {
    global void execute(SchedulableContext sc){
        //OMS status activation does not depend on Date_Closed__c any more
        list<section__c> secLst = [select id , Date_Closed__c , OMS_Disabled_Date__c, OMS_Activation_Date__c from section__c where  OMS_Disabled_Date__c = today or OMS_Activation_Date__c = today  ];
        system.debug('Count of Section Objects=' + secLst.size());
         try{
            update secLst;
            }catch(Exception e)
            {
                system.debug('Failed to update SectionLst ' + secLst);
            }
    }
    
}