src/objects/Section_Product_Link__c.object
<CustomObject>
    <description>Junction object between section and section product tables</description>
    <fields>
        <fullName>IsPublishWizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SharedKey__c</fullName>
        <formula>Section__r.Group__r.Group_Number__c &amp; &quot;s&quot; &amp; Section__r.Section_Number__c &amp; &quot;pr&quot; &amp;  Product__r.Rate_Code__c</formula>
        <label>Shared Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
Section__r.Status__c == &apos;Draft&apos;, Section__r.Status__c,
IF(
Date_closed__c &lt;= TODAY(), &apos;Closed&apos;,
IF(
Product__r.Status__c = &apos;Component Withdrawn&apos;,&apos;Component Withdrawn&apos;,
IF(
Withdrawn_Date__c &lt;= TODAY(), &apos;Withdrawn&apos;,
IF(
Start_Date__c &gt; TODAY(), &apos;Pending&apos;,
Section__r.Status__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>Section__r.Group__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section Product Link</label>
    <nameField>
        <label>Section Product Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section Product Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/splTriggerHandler.cls
public class splTriggerHandler{
    
    //Syncs group fields across other versions (as dictated in relevant field set)
    public Void syncSPLFields(){
		//Check if the trigger is on or off
        if(Label.GRP_SyncFields.toUpperCase() == 'TRUE'){

			guUtil utility = new guUtil();
			utility.syncFields('Section_Product_Link__c', 'SharedKey__c, Version__c', 'Version__c', 'SharedKey__c');
			
        }
    }
	
	
	//WHICS Fields validation
    public Void whicsValidation(){
        
        //exclude records if they have come from the publish wizard
        list<Section_Product_Link__c> newSplLst = (List<Section_Product_Link__c>)Trigger.NEW;
        Boolean isPublishWizard = newSplLst[0].IsPublishWizard__c;

        if(Label.WHICS_Val.toUpperCase() == 'TRUE' && isPublishWizard == false){
            guUtil utility = new guUtil();
			utility.lockedFields('Section_Product_Link__c', 'Status__c');
        }else{
            //reset the publish wizard token for all records
            for(Section_Product_Link__c spl :(List<Section_Product_Link__c>)Trigger.NEW){
                spl.IsPublishWizard__c = false;
            }
        }
        
    }
    
}